/*
 * This source file was generated by the Gradle 'init' task
 */
package basic.exercism;

import basic.exercism.squeakyclean.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        SqueakyClean.clean("__abc-X--429-skql");
    }
}
