/*
 * This source file was generated by the Gradle 'init' task
 */
package basic.exercism;

import basic.exercism.squeakyclean.*;
import basic.exercism.needforspeed.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        SqueakyClean.clean("__abc-X--429-skql");

        var car = new NeedForSpeed(1, 99);
        car.drive();

        car.batteryDrained();
        car.distanceDriven();
    }
}
