/*
 * This source file was generated by the Gradle 'init' task
 */
package basic.exercism;

import basic.exercism.loglevels.LogLevels;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    
    public static void main(String[] args) {
        System.out.println("Run exercism");

        String message = "[WARNING]:  Disk almost full";
        System.out.println(LogLevels.message(message));

        String message2 = "[WARNING]:   \\tTimezone not set  \\r\\n";
        System.out.println(LogLevels.message(message2));
        System.out.println(LogLevels.logLevel(message2));
        System.out.println(LogLevels.reformat(message2));
    }
}
